
# 12-09-2021 Ml Assignment 1
### The file contains hiring statistcs for a company such as experiance of candidate, test score and interview score, based on these parameters HR has to decide the salary. Build machine learning model for HR department that helps to decide the salaraies for the future candidates.

In [3]:
import pandas as pd
import numpy as np 
from sklearn import linear_model
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# Replacimg the word with a number by giving the values 

In [4]:
import pandas as pd
df=pd.read_csv('hiring.csv')
values={'five':5, 'two':2, 'seven':7, 'three':3 , 'ten':10, 'eleven':11}
df=df.replace({"experience":values})
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

# calculatimg the mean for the experience 

In [5]:
df.experience.mean()

6.333333333333333

# Replacimg the mean value 

In [7]:
df.experience=df.experience.fillna(df.experience.mean())
df['experience']=df['experience'].astype(int)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [9]:
new_df=df.rename(columns={'test_score(out of 10)':'test_score','salary($)':'salary'})
new_df

experience  test_score  interview_score(out of 10)  salary
0           6         8.0                           9   50000
1           6         8.0                           6   45000
2           5         6.0                           7   60000
3           2        10.0                          10   65000
4           7         9.0                           6   70000
5           3         7.0                          10   62000
6          10         NaN                           7   72000
7          11         7.0                           8   80000

In [11]:
new_df.test_score.mean()

7.857142857142857

In [14]:
new_df.test_score =new_df.test_score.fillna(new_df.test_score.mean())
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           6                    8.0                           9      50000
1           6                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [24]:
df2=new_df.round({"test_score":1})
df2


experience  test_score  interview_score(out of 10)  salary
0           6         8.0                           9   50000
1           6         8.0                           6   45000
2           5         6.0                           7   60000
3           2        10.0                          10   65000
4           7         9.0                           6   70000
5           3         7.0                          10   62000
6          10         7.9                           7   72000
7          11         7.0                           8   80000

In [25]:
reg=linear_model.LinearRegression()
reg.fit(df2.drop('salary',axis='columns'),df2.salary)

LinearRegression()

In [29]:
reg.predict([[5,4,3]])

array([40058.28491675])

In [30]:
reg.coef_

array([2820.58695176, 1330.68676131, 2928.45205703])

In [31]:
reg.intercept_

11847.246941660756

In [32]:
2820.58695176*5+1330.68676131*4+2928.45205703*3+11847.246941660756

40058.284916790755

# predicting the salary 

In [33]:
reg.predict([[9,6,7]])

array([65715.8144745])

In [34]:
reg.coef_

array([2820.58695176, 1330.68676131, 2928.45205703])

In [35]:
reg.intercept_

11847.246941660756

In [36]:
2820.58695176*9+1330.68676131*6+2928.45205703*7+11847.246941660756

65715.81447457075

In [38]:
reg.predict([[6,8,9]])

array([65772.33125589])